# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNavigation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNavigation

  target 'reactNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNavigation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNavigation-tvOS

  target 'reactNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
